"""add graph jobs

Revision ID: fb2d63b85ad8
Revises: eba17c8732ad
Create Date: 2026-07-04 19:01:35.985966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb2d63b85ad8'
down_revision: Union[str, Sequence[str], None] = 'eba17c8732ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('transactions_considered', sa.Integer(), nullable=True),
    sa.Column('truncated', sa.Boolean(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'done', 'failed')", name='ck_graph_jobs_status_valid'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_jobs_created_at'), 'graph_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_graph_jobs_id'), 'graph_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_graph_jobs_requested_by_user_id'), 'graph_jobs', ['requested_by_user_id'], unique=False)
    op.create_index(op.f('ix_graph_jobs_status'), 'graph_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_jobs_status'), table_name='graph_jobs')
    op.drop_index(op.f('ix_graph_jobs_requested_by_user_id'), table_name='graph_jobs')
    op.drop_index(op.f('ix_graph_jobs_id'), table_name='graph_jobs')
    op.drop_index(op.f('ix_graph_jobs_created_at'), table_name='graph_jobs')
    op.drop_table('graph_jobs')
    # ### end Alembic commands ###
